package direct_thread_item

const Placeholder = "placeholder"
const Text = "text"
const Hashtag = "hashtag"
const Location = "location"
const Profile = "profile"
const Media = "media"
const MediaShare = "media_share"
const ExpiringMedia = "raven_media"
const Like = "like"
const ActionLog = "action_log"
const Reaction = "reaction"
const ReelShare = "reel_share"
const StoryShare = "story_share"
const Link = "link"
const LiveVideoShare = "live_video_share"
const LiveViewerInvite = "live_viewer_invite"
const ProductShare = "product_share"
const VideoCallEvent = "video_call_event"
