package models

type User struct {
	Username                       string `json:"username,omitempty"`
	HasAnonymousProfilePicture     bool   `json:"has_anonymous_profile_picture,omitempty"`
	HasHighlightReels              bool   `json:"has_highlight_reels,omitempty"`
	IsFavorite                     bool   `json:"is_favorite,omitempty"`
	IsFavoriteForStories           bool   `json:"is_favorite_for_stories,omitempty"`
	IsFavoriteForHighlights        bool   `json:"is_favorite_for_highlights,omitempty"`
	IsInterestAccount              bool   `json:"is_interest_account,omitempty"`
	canBeReportedAsFraud           bool
	ProfilePicUrl                  string               `json:"profile_pic_url,omitempty"`
	ProfilePicId                   string               `json:"profile_pic_id,omitempty"`
	Permission                     bool                 `json:"permission,omitempty"`
	FullName                       string               `json:"full_name,omitempty"`
	UserId                         string               `json:"user_id,omitempty"`
	Pk                             int64                `json:"pk,omitempty"`
	Id                             *int64               `json:"id,omitempty"`
	IsVerified                     bool                 `json:"is_verified,omitempty"`
	IsPrivate                      bool                 `json:"is_private,omitempty"`
	CoeffWeight                    interface{}          `json:"coeff_weight,omitempty"`
	FriendshipStatus               *FriendshipStatus    `json:"friendship_status,omitempty"`
	HdProfilePicVersions           []ImageCandidate     `json:"hd_profile_pic_versions,omitempty"`
	Byline                         interface{}          `json:"byline,omitempty"`
	SearchSocialContext            interface{}          `json:"search_social_context,omitempty"`
	UnseenCount                    interface{}          `json:"unseen_count,omitempty"`
	MutualFollowersCount           int                  `json:"mutual_followers_count,omitempty"`
	FollowerCount                  int                  `json:"follower_count,omitempty"`
	SearchSubtitle                 string               `json:"search_subtitle,omitempty"`
	SocialContext                  interface{}          `json:"social_context,omitempty"`
	MediaCount                     int                  `json:"media_count,omitempty"`
	FollowingCount                 int                  `json:"following_count,omitempty"`
	FollowingTagCount              int                  `json:"following_tag_count,omitempty"`
	IsBusiness                     bool                 `json:"is_business,omitempty"`
	UserTagsCount                  int                  `json:"usertags_count,omitempty"`
	ProfileContext                 interface{}          `json:"profile_context,omitempty"`
	Biography                      string               `json:"biography,omitempty"`
	GeoMediaCount                  int                  `json:"geo_media_count,omitempty"`
	IsUnpublished                  bool                 `json:"is_unpublished,omitempty"`
	AllowContactsSync              interface{}          `json:"allow_contacts_sync,omitempty"`
	ShowFeedBizConversionIcon      interface{}          `json:"show_feed_biz_conversion_icon,omitempty"`
	AutoExpandChaining             interface{}          `json:"auto_expand_chaining,omitempty"`
	CanBoostPost                   interface{}          `json:"can_boost_post,omitempty"`
	IsProfileActionNeeded          bool                 `json:"is_profile_action_needed,omitempty"`
	HasChaining                    bool                 `json:"has_chaining,omitempty"`
	HasRecommendAccounts           bool                 `json:"has_recommend_accounts,omitempty"`
	ChainingSuggestions            []ChainingSuggestion `json:"chaining_suggestions,omitempty"`
	IncludeDirectBlacklistStatus   interface{}          `json:"include_direct_blacklist_status,omitempty"`
	CanSeeOrganicInsights          bool                 `json:"can_see_organic_insights,omitempty"`
	HasPlacedOrders                bool                 `json:"has_placed_orders,omitempty"`
	CanConvertToBusiness           bool                 `json:"can_convert_to_business,omitempty"`
	ConvertFromPages               interface{}          `json:"convert_from_pages,omitempty"`
	ShowBusinessConversionIcon     bool                 `json:"show_business_conversion_icon,omitempty"`
	ShowConversionEditEntry        bool                 `json:"show_conversion_edit_entry,omitempty"`
	ShowInsightsTerms              bool                 `json:"show_insights_terms,omitempty"`
	CanCreateSponsorTags           interface{}          `json:"can_create_sponsor_tags,omitempty"`
	HdProfilePicUrlInfo            *ImageCandidate      `json:"hd_profile_pic_url_info,omitempty"`
	UserTagReviewEnabled           interface{}          `json:"usertag_review_enabled,omitempty"`
	ProfileContextMutualFollowIds  interface{}          `json:"profile_context_mutual_follow_ids,omitempty"`
	ProfileContextLinksWithUserIds []Link               `json:"profile_context_links_with_user_ids,omitempty"`
	HasBiographyTranslation        bool                 `json:"has_biography_translation,omitempty"`
	TotalIGTVVideos                int                  `json:"total_igtv_videos,omitempty"`
	TotalArEffects                 int                  `json:"total_ar_effects,omitempty"`
	CanLinkEntitiesInBio           bool                 `json:"can_link_entities_in_bio,omitempty"`
	BiographyWithEntities          *BiographyEntities   `json:"biography_with_entities,omitempty"`
	MaxNumLinkedEntitiesInBio      int                  `json:"max_num_linked_entities_in_bio,omitempty"`
	BusinessContactMethod          string               `json:"business_contact_method,omitempty"`
	HighlightReShareDisabled       bool                 `json:"highlight_reshare_disabled,omitempty"`
	/*
	 * Business category.
	 */
	Category                       string      `json:"category,omitempty"`
	DirectMessaging                string      `json:"direct_messaging,omitempty"`
	PageName                       interface{} `json:"page_name,omitempty"`
	FbPageCallToActionId           string      `json:"fb_page_call_to_action_id,omitempty"`
	IsCallToActionEnabled          bool        `json:"is_call_to_action_enabled,omitempty"`
	AccountType                    int         `json:"account_type,omitempty"`
	PublicPhoneCountryCode         string      `json:"public_phone_country_code,omitempty"`
	PublicPhoneNumber              string      `json:"public_phone_number,omitempty"`
	ContactPhoneNumber             string      `json:"contact_phone_number,omitempty"`
	Latitude                       float64     `json:"latitude,omitempty"`
	Longitude                      float64     `json:"longitude,omitempty"`
	AddressStreet                  string      `json:"address_street,omitempty"`
	Zip                            string      `json:"zip,omitempty"`
	CityId                         float64     `json:"city_id,omitempty"` // 64-bit number.
	CityName                       string      `json:"city_name,omitempty"`
	PublicEmail                    string      `json:"public_email,omitempty"`
	IsNeedy                        bool        `json:"is_needy,omitempty"`
	ExternalUrl                    string      `json:"external_url,omitempty"`
	ExternalLynxUrl                string      `json:"external_lynx_url,omitempty"`
	Email                          string      `json:"email,omitempty"`
	CountryCode                    int         `json:"country_code,omitempty"`
	Birthday                       interface{} `json:"birthday,omitempty"`
	NationalNumber                 float64     `json:"national_number,omitempty"` // Really int but may be >32bit.
	Gender                         int         `json:"gender,omitempty"`
	PhoneNumber                    string      `json:"phone_number,omitempty"`
	NeedsEmailConfirm              interface{} `json:"needs_email_confirm,omitempty"`
	IsActive                       bool        `json:"is_active,omitempty"`
	BlockAt                        interface{} `json:"block_at,omitempty"`
	AggregatePromoteEngagement     interface{} `json:"aggregate_promote_engagement,omitempty"`
	FBUID                          interface{} `json:"fbuid,omitempty"`
	PageId                         interface{} `json:"page_id,omitempty"`
	CanClaimPage                   bool        `json:"can_claim_page,omitempty"`
	FbPageCallToActionIxAppId      int         `json:"fb_page_call_to_action_ix_app_id,omitempty"`
	FbPageCallToActionIxUrl        string      `json:"fb_page_call_to_action_ix_url,omitempty"`
	CanCrossPostWithoutFbToken     bool        `json:"can_crosspost_without_fb_token,omitempty"`
	FbPageCallToActionIxPartner    string      `json:"fb_page_call_to_action_ix_partner,omitempty"`
	ShoppablePostsCount            int         `json:"shoppable_posts_count,omitempty"`
	ShowShoppableFeed              bool        `json:"show_shoppable_feed,omitempty"`
	ShowAccountTransparencyDetails bool        `json:"show_account_transparency_details,omitempty"`
	/*
	 * Unix "taken_at" timestamp of the newest item in their story reel.
	 */
	LatestReelMedia        int64       `json:"latest_reel_media,omitempty"`
	HasUnseenBestiesMedia  bool        `json:"has_unseen_besties_media,omitempty"`
	AllowedCommenterType   string      `json:"allowed_commenter_type,omitempty"`
	ReelAutoArchive        string      `json:"reel_auto_archive,omitempty"`
	IsDirectAppInstalled   bool        `json:"is_directapp_installed,omitempty"`
	BestiesCount           int         `json:"besties_count,omitempty"`
	CanBeTaggedAsSponsor   bool        `json:"can_be_tagged_as_sponsor,omitempty"`
	CanFollowHashtag       bool        `json:"can_follow_hashtag,omitempty"`
	HasProfileVideoFeed    bool        `json:"has_profile_video_feed,omitempty"`
	IsVideoCreator         bool        `json:"is_video_creator,omitempty"`
	ShowBestiesBadge       bool        `json:"show_besties_badge,omitempty"`
	ScreenShotted          bool        `json:"screenshotted,omitempty"`
	Nametag                *Nametag    `json:"nametag,omitempty"`
	School                 interface{} `json:"school,omitempty"`
	IsBestie               bool        `json:"is_bestie,omitempty"`
	LiveSubscriptionStatus string      `json:"live_subscription_status,omitempty"`
}
